### PR TITLE
Disable cache in docker if event is `schedule` 

### PR DESCRIPTION
**Pull request by Antonov548**

### CODE REVIEW

**Comment by krlmlr** [comment]
The cache should also be ignored for `workflow_dispatch`, we can use that for testing too.

**Comment by Antonov548** [comment]
Currently it's failing: https://github.com/cynkra/rig-ubuntu-igraph/actions/runs/7274206412/job/19819649291 
Don't see reason, but will try to find out.

**Comment by krlmlr** [comment]
Outdated apt cache. I'm on it.

Something else: Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/


https://github.com/cynkra/rig-ubuntu-igraph/actions/runs/7274206412/job/19819649291#step:6:20

**Comment by krlmlr** [comment]
I restarted the build, expecting a green build now.

**Comment by krlmlr** [comment]
Do we need `[ ... = ... ]` or `[[ ... == ... ]]` ?

```sh
[ 'a' == 'a' ] && echo ok
# zsh: = not found
[[ 'a' == 'a' ]] && echo ok
# ok
```

**Comment by Antonov548** [comment]
Is `no-cache` property doesn't work if `from` is specified?

**Comment by krlmlr** [comment]
No, I just found this other code in one of the other repositories. I like it better because the cache is still updated with a scheduled or dispatched build. Sorry for the duplication of work.

**Comment by krlmlr** [comment]
Thanks!

**Comment by Antonov548** [comment]
> No, I just found this other code in one of the other repositories. I like it better because the cache is still updated with a scheduled or dispatched build. Sorry for the duplication of work.

Oh, I see. Looks good.

**Pull request merged**
